############################
## PROCESS-VIRTUAL-COHORT ##
############################

# Process virtual cohorts generated by create-and-run-virtual-cohort.R
# Note that the process requires roughly 4.5 times the result file size
# in RAM. It is often better to segment generation in the generation 
# code (create-and-run-virtual-cohort.R).

source("functions_all.R")

# Set directory where the results are located. Typically, not somewhere
# synced to GitHub (100,000 individuals => 100 GB raw output).
# Can be tailored to depend on the machine used. 
if (grepl("node", Sys.info()["nodename"])) {
  OUTPUT_NAS = "/home/jarino/OUTPUT_NAS_small/within-to-between-hosts"
} else {
  OUTPUT_LOCAL = "/home/jarino/OUTPUT_local/within-to-between-hosts"
}

# Load the file. Let's do the latest one for now..
file_name_base = "sim_P0100000_DT20240526-225526"
cohort = 
  readRDS(sprintf("%s/%s_merged.Rds",
                  OUTPUT_LOCAL, file_name_base))
COHORT = cohort$cohort

###
### STATE VARIABLES
###
# Make a list with each entry the state variables. Assumes all 
# individuals have the same time output and state variables
# Shift time to start at tau_I, because up to then, we are in the initial
# time delay part.
STATE_VARS = list()
for (n in colnames(COHORT[[1]])) {
  if (n == "time") {
    STATE_VARS[[n]] = COHORT[[1]][,"time"]
    idx_tauI = which(STATE_VARS$time==cohort$parameters$tau_I[1])[1]
    STATE_VARS[[n]] = 
      STATE_VARS[[n]][idx_tauI:length(STATE_VARS[[n]])] -
      cohort$parameters$tau_I[1]
  } else { #if ((n != "A_I") && (n != "A_R")) {
    STATE_VARS[[n]] = mat.or.vec(nr = dim(COHORT[[1]])[1], 
                                 nc = length(COHORT))
    for (i in 1:length(COHORT)) {
      STATE_VARS[[n]][,i] = COHORT[[i]][,n]
    }
    STATE_VARS[[n]] = STATE_VARS[[n]][idx_tauI:dim(STATE_VARS[[n]])[1],]
  }
}

# Make a matrix with S_max values as columns to be able to compute Phi
S_max_tmp = mat.or.vec(nr = dim(STATE_VARS$S)[1],
                       nc = dim(STATE_VARS$S)[2])
for (c in 1:dim(STATE_VARS$S)[2]) {
  S_max_tmp[,c] = rep(cohort$parameters$S_max[c],
                      dim(STATE_VARS$S)[1])
}
STATE_VARS$Phi = (S_max_tmp-(STATE_VARS$S+STATE_VARS$R)) / S_max_tmp * 100
# Compute transmission
alpha = 16.422
k_v = 7.49
STATE_VARS$beta_hat = 
  STATE_VARS$V ^ alpha / 
  (k_v ^ alpha + STATE_VARS$V ^ alpha)


###
### SUMMARIES OF STATE VARIABLES
###
# Create summary view for state variables. 

# Make list of variables we want to process
names_variables = setdiff(c(colnames(COHORT[[1]]), "Phi", "beta_hat"),
                          c("time", "A_I", "A_R"))
SUMMARIES = list()
for (n in names_variables) {
  SUMMARIES[[n]] = t(apply(STATE_VARS[[n]], 1, 
                           function(x) 
                             quantile(x, 
                                      probs = c(0.025,0.25,0.5,0.75,0.975))))
  SUMMARIES[[n]] = as.data.frame(SUMMARIES[[n]])
  SUMMARIES[[n]]$mean = apply(STATE_VARS[[n]], 1, mean)
}
# Which of the patients are in the different zones?
SUMMARIES$lung_loss = data.frame(max = apply(STATE_VARS$Phi, 2, max))
SUMMARIES$lung_loss$outcome = 
  findInterval(SUMMARIES$lung_loss$max,
               vec = c(0, 75, 85, 100))


# Prepare right censored data: for individuals who die, write down time
# of death this happens (>=85% lung cell loss)
STATE_VARS$idx_censored = rep(NA, dim(STATE_VARS$V)[2])
STATE_VARS$time_censored = rep(NA, dim(STATE_VARS$V)[2])
for (i in 1:dim(STATE_VARS$V)[2]) {
  if (SUMMARIES$lung_loss$outcome[i] == 3) {
    STATE_VARS$idx_censored[i] = which(STATE_VARS$Phi[,i]>=85)[1]
    STATE_VARS$time_censored[i] = STATE_VARS$time[STATE_VARS$idx_censored[i]]
  }
}
# Write down death times
SUMMARIES$time_of_death = 
  sort(STATE_VARS$time_censored[!is.na(STATE_VARS$time_censored)])
# Do the same for hospitalisations
STATE_VARS$idx_hosp = rep(NA, dim(STATE_VARS$V)[2])
STATE_VARS$time_hosp = rep(NA, dim(STATE_VARS$V)[2])
for (i in 1:dim(STATE_VARS$V)[2]) {
  if (SUMMARIES$lung_loss$outcome[i] == 2) {
    STATE_VARS$idx_hosp[i] = which(STATE_VARS$Phi[,i]>=75)[1]
    STATE_VARS$time_hosp[i] = STATE_VARS$time[STATE_VARS$idx_hosp[i]]
  }
}
# Write down hospitalisation times
SUMMARIES$time_of_hospitalisation = 
  sort(STATE_VARS$time_hosp[!is.na(STATE_VARS$time_hosp)])
# Now recoveries. Suppose Phi gets larger than some threshold theta
threshold = 15
idx_uncensored = which(is.na(STATE_VARS$idx_censored))
min_phi = apply(STATE_VARS$Phi, 2, min)
idx_min_phi = c()
idx_cross_threshold = c()
for (i in 1:dim(STATE_VARS$Phi)[2]) {
  idx_min_phi = c(idx_min_phi, which(STATE_VARS$Phi[,i] == min_phi[i]))
  idx_tmp = idx_min_phi[i]:dim(STATE_VARS$Phi)[1]
  idx_cross_threshold = c(idx_cross_threshold,
                          which(STATE_VARS$Phi[idx_tmp,i] <= threshold)[1])
}
SUMMARIES$time_of_recovery = 
  sort(STATE_VARS$time[idx_cross_threshold[idx_uncensored]])

# Get viral loads and beta_hat summaries for each type of patient (severities
# in 1,2,3). 
SUMMARIES$V_outcome = list()
SUMMARIES$beta_hat_outcome = list()
SUMMARIES$beta_hat_max_value_outcome = list()
SUMMARIES$beta_hat_max_idx_outcome = list()
SUMMARIES$beta_hat_max_time_outcome = list()
for (s in sort(unique(SUMMARIES$lung_loss$outcome))) {
  tmp = STATE_VARS$V[, which(SUMMARIES$lung_loss$outcome == s)]
  tmp_beta_hat = 
    tmp ^ alpha / 
    (k_v ^ alpha + tmp ^ alpha)
  # Value of the max
  SUMMARIES$beta_hat_max_value_outcome[[s]] = 
    apply(tmp_beta_hat, 2, max)
  SUMMARIES$beta_hat_max_idx_outcome[[s]] = 
    unlist(apply(tmp_beta_hat, 2,
                 function(x) which(x == max(x))))
  SUMMARIES$beta_hat_max_time_outcome[[s]] = 
    STATE_VARS$time[SUMMARIES$beta_hat_max_idx_outcome[[s]]]
  SUMMARIES$V_outcome[[s]] = t(apply(tmp, 1, 
                                     function(x) 
                                       quantile(x, 
                                                probs = c(0.025,0.25,0.5,0.75,0.975))))
  SUMMARIES$V_outcome[[s]] = as.data.frame(SUMMARIES$V_outcome[[s]])
  SUMMARIES$V_outcome[[s]]$mean = apply(tmp, 1, mean)
  SUMMARIES$beta_hat_outcome[[s]] = t(apply(tmp_beta_hat, 1, 
                                            function(x) 
                                              quantile(x, 
                                                probs = c(0.025,0.25,0.5,0.75,0.975))))
  SUMMARIES$beta_hat_outcome[[s]] = as.data.frame(SUMMARIES$beta_hat_outcome[[s]])
  SUMMARIES$beta_hat_outcome[[s]]$mean = apply(tmp_beta_hat, 1, mean)
}
# # Add severity 4, combining 2 and 3.
# tmp = STATE_VARS$V[, which(SUMMARIES$lung_loss$outcome %in% c(2,3))]
# tmp_beta_hat = 
#   tmp ^ alpha / 
#   (k_v ^ alpha + tmp ^ alpha)
# # Value of the max
# SUMMARIES$beta_hat_max_value_outcome[[4]] = 
#   apply(tmp_beta_hat, 2, max)
# SUMMARIES$beta_hat_max_idx_outcome[[4]] = 
#   unlist(apply(tmp_beta_hat, 2,
#                function(x) which(x == max(x))))
# SUMMARIES$beta_hat_max_time_outcome[[4]] = 
#   STATE_VARS$time[SUMMARIES$beta_hat_max_idx_outcome[[4]]]
# SUMMARIES$V_outcome[[4]] = t(apply(tmp, 1, 
#                                    function(x) 
#                                      quantile(x, 
#                                               probs = c(0.025,0.25,0.5,0.75,0.975))))
# SUMMARIES$V_outcome[[4]] = as.data.frame(SUMMARIES$V_outcome[[4]])
# SUMMARIES$V_outcome[[4]]$mean = apply(tmp, 1, mean)
# SUMMARIES$beta_hat_outcome[[4]] = t(apply(tmp_beta_hat, 1, 
#                                           function(x) 
#                                             quantile(x, 
#                                                      probs = c(0.025,0.25,0.5,0.75,0.975))))
# SUMMARIES$beta_hat_outcome[[4]] = as.data.frame(SUMMARIES$beta_hat_outcome[[4]])
# SUMMARIES$beta_hat_outcome[[4]]$mean = apply(tmp_beta_hat, 1, mean)

# Now consider viral load as a function of IFB
# Get viral loads and beta_hat summaries for each type of patient (severities
# in 1,2,3).
min_FB = min(STATE_VARS$F_B)
max_FB = max(STATE_VARS$F_B)
values_FB = seq(min_FB, max_FB, length.out = 50)
SUMMARIES$V_fct_FB = list()
SUMMARIES$beta_hat_fct_FB = list()
for (s in sort(unique(SUMMARIES$lung_loss$outcome))) {
  tmp_V = STATE_VARS$V[, which(SUMMARIES$lung_loss$outcome == s)]
  tmp_FB = STATE_VARS$F_B[, which(SUMMARIES$lung_loss$outcome == s)]
  tmp_values_FB = mat.or.vec(nr = length(values_FB),
                             nc = dim(tmp_V)[2])
  for (i in 1:dim(tmp_V)[2]) {
    if (i %% 10000 == 0) {
      writeLines(paste0("s=", s, " i=", i))
    }
    tmp = data.frame(FB = tmp_FB[,i],
                     V = tmp_V[,i])
    tmp_coeffs = lm(V ~ FB, data = tmp)$coefficients
    tmp_values_FB[,i] = tmp_coeffs[1] + tmp_coeffs[2]*values_FB
  }
  SUMMARIES$V_fct_FB[[s]] = t(apply(tmp_values_FB, 1, 
                                    function(x) 
                                      quantile(x, 
                                               probs = c(0.025,0.25,0.5,0.75,0.975))))
  SUMMARIES$V_fct_FB[[s]] = as.data.frame(SUMMARIES$V_fct_FB[[s]])
  SUMMARIES$V_fct_FB[[s]]$mean = apply(tmp_values_FB, 1, mean)
}

saveRDS(STATE_VARS, file = sprintf("%s/%s_state-vars.Rds",
                                  OUTPUT_LOCAL, 
                                  file_name_base))
saveRDS(SUMMARIES, file = sprintf("%s/%s_summaries.Rds",
                                  OUTPUT_LOCAL, 
                                  file_name_base))
