#!/bin/bash
set -e

echo "Running the sensitivity analysis simulations..."
julia run-sensitivity-analysis-sims.jl

echo "Processing the sensitivity analysis PRCC..."
Rscript process-PRCC.R

echo "Plotting the PRCC figures..."
Rscript plot-Figure-03-B1-PRCC-within-host.R

echo "Sensitivity analysis pipeline complete!"
